### Get all products
GET http://localhost:5001/api/products

### Create new product
POST http://localhost:5001/api/products
Content-Type: application/json

{
    "name": "Laptop",
    "category": "Laptops",
    "quantity": 10,
    "price": 500,
    "description": "Laptop description"
}

### Get product by id
GET http://localhost:5001/api/products/67a759a5d1ef2310394cdf9d

### Delete product by id
DELETE http://localhost:5001/api/products/67a759a5d1ef2310394cdf9d