import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import axios from 'axios';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

function Profile() {
  const user = JSON.parse(localStorage.getItem('user'));
  const navigate = useNavigate();
  const [pets, setPets] = useState([]);

  useEffect(() => {
    if (!user) {
      navigate('/login');
      return;
    }

    const fetchPets = async () => {
      try {
        const res = await axios.get(`http://localhost:5000/api/users/pets/${user._id}`);
        setPets(res.data);
      } catch (error) {
        console.error('Failed to fetch pets:', error.message);
      }
    };
    fetchPets();
  }, [navigate, user]);

  if (!user) return null;

  const handleDeleteAccount = async () => {
    if (window.confirm('Are you sure you want to delete your account? This action cannot be undone.')) {
      try {
        await axios.delete(`http://localhost:5000/api/users/${user._id}`);
        localStorage.removeItem('user');
        alert('Account deleted successfully!');
        navigate('/login');
      } catch (error) {
        alert('Delete failed: ' + error.message);
      }
    }
  };

  const handleDeletePet = async (id) => {
    if (window.confirm('Are you sure you want to delete this pet?')) {
      try {
        await axios.delete(`http://localhost:5000/api/users/pets/${id}`);
        setPets(pets.filter(pet => pet._id !== id));
        alert('Pet deleted successfully!');
      } catch (error) {
        alert('Delete failed: ' + error.message);
      }
    }
  };

  const handleDownloadProfile = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.setTextColor(0, 123, 255);
    doc.text('Pet Care User Profile', 105, 20, { align: 'center' });
    doc.setFontSize(12);
    doc.setTextColor(85, 85, 85);
    doc.text(`Profile for ${user.username}`, 105, 30, { align: 'center' });

    const profileData = [
      ['First Name', user.firstName],
      ['Last Name', user.lastName],
      ['Username', user.username],
      ['Email', user.email],
      ['Phone', user.phone]
    ];

    autoTable(doc, {
      startY: 40,
      head: [['Field', 'Value']],
      body: profileData,
      theme: 'grid',
      styles: { fontSize: 10, cellPadding: 3 },
      headStyles: { fillColor: [0, 123, 255], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [240, 240, 240] },
    });

    if (pets.length > 0) {
      doc.setFontSize(14);
      doc.setTextColor(0, 123, 255);
      doc.text('Your Pets', 105, doc.lastAutoTable.finalY + 20, { align: 'center' });

      const petData = pets.map(pet => [
        pet.petName,
        pet.breed,
        new Date(pet.birthday).toLocaleDateString(),
        pet.age,
        `${pet.weight} kg`,
        pet.specialConditions || 'None'
      ]);

      autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 30,
        head: [['Pet Name', 'Breed', 'Birthday', 'Age', 'Weight', 'Special Conditions']],
        body: petData,
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 3 },
        headStyles: { fillColor: [0, 123, 255], textColor: [255, 255, 255] },
        alternateRowStyles: { fillColor: [240, 240, 240] },
      });
    } else {
      doc.setFontSize(12);
      doc.setTextColor(85, 85, 85);
      doc.text('No pets added yet.', 105, doc.lastAutoTable.finalY + 20, { align: 'center' });
    }

    doc.setFontSize(8);
    doc.setTextColor(85, 85, 85);
    doc.text('Generated by Online Pet Care System', 105, doc.internal.pageSize.height - 10, { align: 'center' });
    doc.save(`${user.username}_profile.pdf`);
    alert('Profile and pet details downloaded as PDF!');
  };

  return (
    <div className="container mt-5">
      <div className="card shadow-lg p-4" style={{ borderRadius: '15px', border: 'none' }}>
        <div className="d-flex justify-content-between align-items-center mb-4">
          <h2 className="mb-0" style={{ color: '#007bff', fontWeight: '600' }}>Profile 🐾</h2>
          <div>
            <button 
              onClick={handleDownloadProfile} 
              className="btn btn-outline-success me-2" 
              style={{ borderRadius: '10px' }}
            >
              <i className="fas fa-download me-2"></i> Download Profile
            </button>
            <button 
              onClick={handleDeleteAccount} 
              className="btn btn-outline-danger" 
              style={{ borderRadius: '10px' }}
            >
              <i className="fas fa-trash-alt me-2"></i> Delete Account
            </button>
          </div>
        </div>
        
        <div className="row">
          {/* Profile Photo and Basic Info */}
          <div className="col-md-4 mb-4">
            <div className="card h-100" style={{ borderRadius: '15px', border: 'none', boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)' }}>
              <div className="card-body text-center">
                {user.profilePhoto ? (
                  <img 
                    src={`http://localhost:5000${user.profilePhoto}`} 
                    alt="Profile" 
                    className="img-fluid rounded-circle mb-3" 
                    style={{ 
                      width: '150px', 
                      height: '150px', 
                      objectFit: 'cover', 
                      border: '3px solid #007bff',
                      boxShadow: '0 4px 8px rgba(0, 123, 255, 0.2)'
                    }} 
                  />
                ) : (
                  <div 
                    className="rounded-circle mx-auto mb-3 d-flex align-items-center justify-content-center" 
                    style={{ 
                      width: '150px', 
                      height: '150px', 
                      backgroundColor: '#e9ecef',
                      border: '3px solid #007bff'
                    }}
                  >
                    <i className="fas fa-user fa-4x text-secondary"></i>
                  </div>
                )}
                <h4 className="mb-1">{user.firstName} {user.lastName}</h4>
                <p className="text-muted mb-3">@{user.username}</p>
                <Link 
                  to="/update-profile" 
                  className="btn btn-primary w-100" 
                  style={{ borderRadius: '10px' }}
                >
                  <i className="fas fa-edit me-2"></i> Edit Profile
                </Link>
              </div>
            </div>
          </div>
          
          {/* Contact Information */}
          <div className="col-md-8 mb-4">
            <div className="card h-100" style={{ borderRadius: '15px', border: 'none', boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)' }}>
              <div className="card-header bg-white" style={{ borderRadius: '15px 15px 0 0', borderBottom: '1px solid #e9ecef' }}>
                <h5 className="mb-0" style={{ color: '#007bff' }}>
                  <i className="fas fa-address-card me-2"></i> Contact Information
                </h5>
              </div>
              <div className="card-body">
                <div className="row">
                  <div className="col-md-6 mb-3">
                    <div className="d-flex align-items-center">
                      <div className="rounded-circle d-flex align-items-center justify-content-center me-3" style={{ width: '40px', height: '40px', backgroundColor: '#e6f7ff' }}>
                        <i className="fas fa-envelope text-primary"></i>
                      </div>
                      <div>
                        <p className="text-muted mb-0">Email</p>
                        <p className="mb-0 fw-bold">{user.email}</p>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-6 mb-3">
                    <div className="d-flex align-items-center">
                      <div className="rounded-circle d-flex align-items-center justify-content-center me-3" style={{ width: '40px', height: '40px', backgroundColor: '#e6f7ff' }}>
                        <i className="fas fa-phone text-primary"></i>
                      </div>
                      <div>
                        <p className="text-muted mb-0">Phone</p>
                        <p className="mb-0 fw-bold">{user.phone}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Pets Section */}
        <div className="card" style={{ borderRadius: '15px', border: 'none', boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)' }}>
          <div className="card-header bg-white" style={{ borderRadius: '15px 15px 0 0', borderBottom: '1px solid #e9ecef' }}>
            <div className="d-flex justify-content-between align-items-center">
              <h5 className="mb-0" style={{ color: '#007bff' }}>
                <i className="fas fa-paw me-2"></i> My Pets
              </h5>
              <Link 
                to="/add-pet" 
                className="btn btn-primary btn-sm" 
                style={{ borderRadius: '10px' }}
              >
                <i className="fas fa-plus me-2"></i> Add Pet
              </Link>
            </div>
          </div>
          <div className="card-body">
            {pets.length === 0 ? (
              <div className="text-center py-4">
                <i className="fas fa-paw fa-3x mb-3" style={{ color: '#007bff' }}></i>
                <h5 className="text-muted">No pets added yet</h5>
                <p className="text-muted">Add your first pet to get started!</p>
              </div>
            ) : (
              <div className="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
                {pets.map(pet => (
                  <div key={pet._id} className="col">
                    <div className="card h-100" style={{ borderRadius: '15px', border: 'none', boxShadow: '0 2px 4px rgba(0, 0, 0, 0.05)' }}>
                      <div className="card-body">
                        <h5 className="card-title" style={{ color: '#007bff' }}>
                          <i className="fas fa-paw me-2"></i>{pet.petName}
                        </h5>
                        <div className="pet-details">
                          <p className="mb-2">
                            <i className="fas fa-dog me-2 text-muted"></i>
                            <span className="fw-bold">Breed:</span> {pet.breed}
                          </p>
                          <p className="mb-2">
                            <i className="fas fa-calendar-alt me-2 text-muted"></i>
                            <span className="fw-bold">Birthday:</span> {new Date(pet.birthday).toLocaleDateString()}
                          </p>
                          <p className="mb-2">
                            <i className="fas fa-birthday-cake me-2 text-muted"></i>
                            <span className="fw-bold">Age:</span> {pet.age} years
                          </p>
                          <p className="mb-2">
                            <i className="fas fa-weight me-2 text-muted"></i>
                            <span className="fw-bold">Weight:</span> {pet.weight} kg
                          </p>
                          {pet.specialConditions && (
                            <p className="mb-2">
                              <i className="fas fa-notes-medical me-2 text-muted"></i>
                              <span className="fw-bold">Special Conditions:</span> {pet.specialConditions}
                            </p>
                          )}
                        </div>
                        <div className="d-flex justify-content-end mt-3">
                          <Link 
                            to={`/edit-pet/${pet._id}`} 
                            className="btn btn-outline-primary btn-sm me-2" 
                            style={{ borderRadius: '10px' }}
                          >
                            <i className="fas fa-edit me-1"></i> Edit
                          </Link>
                          <button 
                            onClick={() => handleDeletePet(pet._id)} 
                            className="btn btn-outline-danger btn-sm" 
                            style={{ borderRadius: '10px' }}
                          >
                            <i className="fas fa-trash me-1"></i> Delete
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Profile;